---
name: Tests

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - name: ⬇️ Check out code from GitHub
        uses: actions/checkout@v6.1.0
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: 🏗 Install project dependencies
        run: uv sync --frozen --dev
      - name: 🧪 Run integration tests
        run: uv run pytest
